### ISSUE TITLE
Settings page tabs not appearing when eRoom - Zoom Meetings & Webinar plugin is activated

### ISSUE THREAD

**Issue by polevaultweb** [WPUserManager/wp-user-manager#174]
https://wordpress.org/plugins/eroom-zoom-meetings-webinar/

**Comment by polevaultweb** [comment]
![image](https://user-images.githubusercontent.com/1770201/114671257-cc1b5600-9cfb-11eb-84f5-76659ebf5ed6.png)

**Comment by reygcalantaol** [comment]
@polevaultweb 

This is resolve on this PR https://github.com/WPUserManager/wp-optionskit/pull/7
