### ISSUE TITLE
Activating wp-user-manager breaks "Add Media" button in the page editor screen

### ISSUE THREAD

**Issue by cptsoviet** [WPUserManager/wp-user-manager#22]
When plugin is activated, it creates a "User Shortcodes" dropdown in the page editor window right next to "Add Media". Neither "Add Media" nor "User Shortcodes" dropdowns work afterwards.

**Comment by polevaultweb** [comment]
Is this still happening for you? I can't recreate locally - perhaps it's a clash with another plugin?
