### ISSUE TITLE
[BUG] Profile Cover image does not work

### ISSUE THREAD

**Issue by MarkKevin08** [WPUserManager/wp-user-manager#221]
Description:
A client reported a similar scenario where the uploaded profile cover image does not display.

To replicate:
1.) Edit your profile
2.) Try to upload a cover image
3.) Check the profile, the cover is not displaying.
4.) Check the settings again, It display no file chosen.

Screenshot
![image](https://user-images.githubusercontent.com/49851476/118786035-057b4e80-b8c4-11eb-92a1-7b2c616cdac0.png)

**Comment by polevaultweb** [comment]
This was an issue with the Custom Fields addon, fixed in 2.4.2
