### ISSUE TITLE
When you log in after trying to access a WP admin link should correctly redirect you to that URL

### ISSUE THREAD

**Issue by polevaultweb** [WPUserManager/wp-user-manager#241]
Most of the query strings are stripped so you end up on the admin posts page.

- Ensure 'Lock Access to wp-login.php' is checked in Users > Settings > Login
- When logged out, try to access an edit post link , eg. https://wpum.test/wp/wp-admin/post.php?post=854&action=edit
- Get redirected to the login page with the URL in the redirect_to
- Login
- Get redirect to https://wpum.test/wp/wp-admin/edit.php instead of the edit post page

**Comment by reygcalantaol** [comment]
@polevaultweb 
May I ask the steps how to reproduce this issue?

**Comment by polevaultweb** [comment]
@reygcalantaol updated in the description

**Comment by polevaultweb** [comment]
Did you manage to recreate @reygcalantaol?
