### ISSUE TITLE
Saving settings does not work when running in production mode

### ISSUE THREAD

**Issue by japsen** [WPUserManager/wp-user-manager#26]
When running in production mode, wordpress doesn't allow the user to install themes. 
However for some reason wp-user-manager checks for the "install_themes" permission.
Changing this to "activate_plugins" fixes the issue. 

https://github.com/WPUserManager/wp-user-manager/blob/master/vendor/alessandrotesoro/wp-optionskit/includes/class-wpok-rest-server.php   

Line: 112
		if ( ! current_user_can( 'install_themes' ) ) {

**Comment by alessandrotesoro** [comment]
Hi @japsen 

Sorry for late reply I forgot to write here after I had fixed the issue. An update was issues few months back that fixes the issue 👍
