### ISSUE TITLE
Broken functionality should (not)...

### ISSUE THREAD

**Issue by MarkKevin08** [WPUserManager/wp-user-manager#277]
## Current Outcome

It seems that adding restriction for the paragraphs blocks using Gutenberg displays the restriction message for each blocks:
![image](https://user-images.githubusercontent.com/49851476/165074857-665a0977-1e15-4c27-b9e5-fbd19520b987.png)

Here's the setting of the page:
![image](https://user-images.githubusercontent.com/49851476/165074945-ecce8911-8d09-4dbe-a625-13ab3a14e01f.png)

## Desired Outcome

Ideally, setting the restriction per block should only display the message once.

## Steps to Reproduce

1. create a post using Gutenberg
2. add a restriction for two lines of paragraphs.

## Related

- HS ticket - https://secure.helpscout.net/conversation/1854597010/3173/

## Acceptance Criteria

- [ ]

**Comment by polevaultweb** [comment]
The solution here is to group contiguous blocks and set the restriction at the group level https://cln.sh/Fi3A7g
