### ISSUE TITLE
Restricting menu items by multiple roles should work

### ISSUE THREAD

**Issue by polevaultweb** [WPUserManager/wp-user-manager#281]
## Current Outcome

Currently if you select multiple roles when restricting a menu item, only the last role will be saved

## Desired Outcome

Ideally all roles will be saved and the restriction will work for them all

## Steps to Reproduce

1. Edit a Menu from Appearance > Menus
2. Add a page and restrict it
<img width="518" alt="image" src="https://user-images.githubusercontent.com/1770201/169701993-5eba8064-18c4-47e1-a796-c8a4f8dd4ca2.png">

## Related

- https://wordpress.org/support/topic/cannot-use-multiple-roles-to-filter-menu-items/

## Acceptance Criteria

- [ ] Multiple roles should be saved for menu restriction

**Comment by polevaultweb** [comment]
@reygcalantaol could you look at this next please?

**Comment by reygcalantaol** [comment]
@polevaultweb 
I can't reproduced the issue.

**Comment by polevaultweb** [comment]
@reygcalantaol thanks - me neither. Asked the OP for more detail

**Comment by polevaultweb** [comment]
Customer not come back with more details
