### ISSUE TITLE
Erase Personal Data function is not working

### ISSUE THREAD

**Issue by evrpress** [WPUserManager/wp-user-manager#285]
## Current Outcome

The "Erase Personal Data" functionality sends a confirmation email to the user which includes a link to confirm the action. This just end up either on the login screen.

## Desired Outcome

Like the native behavior a message should be display regardless of the login status of the user

![image](https://user-images.githubusercontent.com/881729/176386859-d146635a-92b1-4226-abd9-c873efcfd201.png)

## Steps to Reproduce

1. Create a user in the WordPress backend
2. Go to Tools => Erase Personal Data
3. Enter the users email at "Add Data Erasure Request"
4. Click on "Send Request"
5. Open the link in an incognito tab (or logg out before)
6. Check the status of the request (which is still pending)

## Related

Same problem is most likely with "Export Personal Data" but not tested

## Acceptance Criteria

- [ ] The Status should change to "Confirmed (x seconds ago)
- [ ] A message should be displayed after visiting the link from the confirmation email

**Comment by reygcalantaol** [comment]
@polevaultweb 
I can't reproduce the issue.
I tested it multiple times.

**Comment by polevaultweb** [comment]
@evrpress what other addons do you have activated? Are you using the Security addon? A screenshot of your settings might help please

**Comment by reygcalantaol** [comment]
@polevaultweb 
Yes, I am using a security addon.
Attached is the settings.
![image](https://user-images.githubusercontent.com/1219402/179536474-ec569429-97c7-45c2-84ff-945d05f685bc.png)

**Comment by polevaultweb** [comment]
@reygcalantaol thanks, but was checking with the original reporter @evrpress

**Comment by wp-user-manager** [comment]
Can't recreate
