### ISSUE TITLE
Error in event handler: RangeError: Maximum call stack size exceeded JS error on account settings

### ISSUE THREAD

**Issue by polevaultweb** [WPUserManager/wp-user-manager#297]
This only happens on the account settings page with some fields, possibly Select 2

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/1770201/184237592-3569ff10-671c-45cb-af69-86a24e490dbd.png">

**Comment by reygcalantaol** [comment]
@polevaultweb 
I can't reproduce the issue but based on the screenshot it looks like the error is coming from "Ghost Inspector - Web Test Recorder" chrome extension.

**Comment by polevaultweb** [comment]
Good spot!
