### ISSUE TITLE
Old password keys causing errors for new ones

### ISSUE THREAD

**Issue by thedanielcho** [WPUserManager/wp-user-manager#302]
## Current Outcome

Currently when trying to reset passwords, if the user either hasn't reset their password before, or uses incognito mode or a browser they don't normally use, using a new link with a new key will work fine and the form will load properly. But if they have opened the page with an older key before, using a new link will cause an error message to display saying the key is expired or some other issue has occurred. If that page is refreshed however, it will then load properly.
I initially thought it might be a cookie related issue, but checking the code, it seems to properly set the cookie when you open the page with the right key and username, but then it doesn't seem to go to the reset() function in the class-wpum-form-password-recovery.php file. But upon a refresh, it does.

## Desired Outcome

Ideally there would be no instances of the page being opened with a new key but then given an error saying said key is expired.

## Steps to Reproduce

1. Find two password reset keys/links for a user, one that is expired and one that is new/not-expired.
2. Open a browser tab in incognito mode with the expired key/link and get the normal error about an expired key.
3. Without closing the incognito window, open the new key/link to see the same error message.
4. Refresh that page to see the page function as it should.

## Related

-

## Acceptance Criteria

- [ ]

**Comment by polevaultweb** [comment]
Superseded by https://github.com/WPUserManager/wp-user-manager/issues/304
