### ISSUE TITLE
Conflict with builders Oxygen builder or Bricks builder or Bricksdance builder.

### ISSUE THREAD

**Issue by MarkKevin08** [WPUserManager/wp-user-manager#311]
## Current Outcome

Upon testing, the issue seems to be starting when using the shortcodes within these builders. I tested this in Bricks Builder.
With the recent updates, subpages are not loading. Unless the [wpum_account] shortcode is loaded in the Gutenberg. The downside with this option, the template designed in any of the builders stated above is not loading, meaning just a blank account page working fine including subpages.

## Desired Outcome

As the client mentioned: I used to just open the builder editor, design the template and insert the shortcode [wpum_account] and done. Everything works including subpages.

## Steps to Reproduce

To test it further,  here's a staging site with one of the builder (Bricks Builder)
https://brickdance.assignit.me/wp-admin/

U: Mohammed_xwolfx

P: H4tGFFaCwbRfez%@U#o3SEVqJRz57gxLmuY@m^5DS5P8Z

Once you login go to account page
[https://brickdance.assignit.me/wp-admin/post.php?post=351&action=edit​​​​​​​](https://brickdance.assignit.me/wp-admin/post.php?post=351&action=edit)

## Related

- https://secure.helpscout.net/conversation/1836784298/3113/

## Acceptance Criteria

- [ ]

**Comment by polevaultweb** [comment]
Fixed with https://github.com/WPUserManager/wp-user-manager/commit/bed9146c68d0d6e811ad8f24de09e3c134dfc0d0
