### ISSUE TITLE
User Role field should not throw array conversion notice

### ISSUE THREAD

**Issue by polevaultweb** [WPUserManager/wp-user-manager#322]
## Current Outcome

Currently User Role field outputs [15-Sep-2022 09:59:35 UTC] PHP Notice:  Array to string conversion in /wp-includes/general-template.php on line 4896 when loading the account with a UR field.

## Desired Outcome

Ideally no notice is thrown

## Steps to Reproduce

1.

## Related

-

## Acceptance Criteria

- [ ]

**Comment by reygcalantaol** [comment]
@polevaultweb 
Unable to reproduce the issue.

**Comment by polevaultweb** [comment]
Neither can I now
