### ISSUE TITLE
Apostrophe in names not searchable through directory search

### ISSUE THREAD

**Issue by MarkKevin08** [WPUserManager/wp-user-manager#341]
## Current Outcome

Upon testing, we cannot search names when using the apostrophe character. For example:

user's name: T'est WPUM Search

This name is only searchable without the character:
![image](https://user-images.githubusercontent.com/49851476/212274685-2fa61811-57bd-478a-9492-26168455dc95.png)

When we include the apostrophe character, there are no results:
![image](https://user-images.githubusercontent.com/49851476/212274769-0ee3c434-7966-49b9-aa8d-cd754afee944.png)

## Desired Outcome

Users should be able to search completely even with the apostrophe character.

## Steps to Reproduce

1. Create a test username with apostrophe character in the name
2. Try to search it completely with the apostrophe

## Related

- https://secure.helpscout.net/conversation/2122838736/4274/

## Acceptance Criteria

- [ ]

**Comment by wp-user-manager** [comment]
Apparently WordPress search handles this.

Bad review due to this bug https://wordpress.org/support/topic/bad-support-for-a-big-issue/

@reygcalantaol could you prioritize please
