### ISSUE TITLE
Test and fix PHP 8.2 issues

### ISSUE THREAD

**Issue by wp-user-manager** [WPUserManager/wp-user-manager#358]
- Run on a site with PHP 8.2
- Fix warnings, errors and notices
- Log any issues that can't be fixed (eg. issues with Carbon Fields plugin)
- 
https://wordpress.org/support/topic/compatibility-with-the-latest-versions-of-php/

**Comment by reygcalantaol** [comment]
@polevaultweb 
These are the deprecated notice coming from the vendor packages.

Deprecated: Return type of WPUM\Carbon_Fields\Pimple\Container::offsetExists($id) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/htmlburger/carbon-fields/core/Pimple/Container.php on line 111

Deprecated: Return type of WPUM\Carbon_Fields\Pimple\Container::offsetGet($id) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/htmlburger/carbon-fields/core/Pimple/Container.php on line 87

Deprecated: Return type of WPUM\Carbon_Fields\Pimple\Container::offsetSet($id, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/htmlburger/carbon-fields/core/Pimple/Container.php on line 70

Deprecated: Return type of WPUM\Carbon_Fields\Pimple\Container::offsetUnset($id) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/htmlburger/carbon-fields/core/Pimple/Container.php on line 120

Deprecated: Creation of dynamic property WPUM\Carbon_Fields\Container\User_Meta_Container::$id is deprecated in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/htmlburger/carbon-fields/core/Container/Container.php on line 188

Deprecated: Creation of dynamic property WPUM\Carbon_Fields\Container\User_Meta_Container::$type is deprecated in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/htmlburger/carbon-fields/core/Container/Container.php on line 190

Deprecated: Return type of WPUM\Brain\Cortex\Route\PriorityRouteCollection::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/PriorityRouteCollection.php on line 62

Deprecated: Return type of WPUM\Brain\Cortex\Route\PriorityRouteCollection::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/PriorityRouteCollection.php on line 69

Deprecated: Return type of WPUM\Brain\Cortex\Route\PriorityRouteCollection::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/PriorityRouteCollection.php on line 76

Deprecated: Return type of WPUM\Brain\Cortex\Route\PriorityRouteCollection::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/PriorityRouteCollection.php on line 83

Deprecated: Return type of WPUM\Brain\Cortex\Route\PriorityRouteCollection::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/PriorityRouteCollection.php on line 90

Deprecated: Return type of WPUM\Brain\Cortex\Route\PriorityRouteCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/PriorityRouteCollection.php on line 97

Deprecated: Return type of WPUM\Brain\Cortex\Route\QueryRoute::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/DerivativeRouteTrait.php on line 41

Deprecated: Return type of WPUM\Brain\Cortex\Route\QueryRoute::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/DerivativeRouteTrait.php on line 50

Deprecated: Return type of WPUM\Brain\Cortex\Route\QueryRoute::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/DerivativeRouteTrait.php on line 59

Deprecated: Return type of WPUM\Brain\Cortex\Route\QueryRoute::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/DerivativeRouteTrait.php on line 67

Deprecated: Return type of WPUM\Brain\Cortex\Route\Route::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/Route.php on line 62

Deprecated: Return type of WPUM\Brain\Cortex\Route\Route::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/Route.php on line 69

Deprecated: Return type of WPUM\Brain\Cortex\Route\Route::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/Route.php on line 76

Deprecated: Return type of WPUM\Brain\Cortex\Route\Route::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Route/Route.php on line 83

Deprecated: Return type of WPUM\Brain\Cortex\Router\RouteFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Router/RouteFilterIterator.php on line 56

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/wpum.test/wp-content/plugins/wp-user-manager/vendor-dist/brain/cortex/src/Cortex/Uri/WordPressUri.php on line 66
