### ISSUE TITLE
Translation for the specific tab not working - personal-data tab

### ISSUE THREAD

**Issue by MarkKevin08** [WPUserManager/wp-user-manager#375]
## Current Outcome

As per testing, and as from the report of the customer - we can change other links on account tab where there is no "-" mark in the name of the link. But could not change "personal-data" and "delete-account" link names. Other tabs came out nicely. Picture of the screen is attached.

Here is my code in WPUM.php

function wpum_account_change_settings_tab_name( $tabs ) {
$tabs['settings']['name'] = esc_html( 'Käyttäjätiedot' );
$tabs['password']['name'] = esc_html( 'Salasana' );
$tabs['privacy']['name'] = esc_html( 'Yksityys' );
$tabs['logout']['name'] = esc_html( 'Uloskirjaus' );
$tabs['personal-data']['name'] = esc_html( 'Yksityiset tiedot' );
$tabs['delete-account']['name'] = esc_html( 'Poista tili' );
return $tabs;
}
add_filter( 'wpum_get_account_page_tabs', 'wpum_account_change_settings_tab_name' );

![image](https://user-images.githubusercontent.com/49851476/233018724-d5bae8f5-35ce-42a7-a411-9647d9ab1823.png)

## Desired Outcome

They should be the same as the other strings within the profile page, which does not have any problem with such customization.

## Steps to Reproduce

1. use the snippet above to test it.

## Related

- https://secure.helpscout.net/conversation/2216205520/4750/

## Acceptance Criteria

- [ ]

**Comment by wp-user-manager** [comment]
@MarkKevin08 have you got the code and screenshot please?

**Comment by MarkKevin08** [comment]
@wp-user-manager , updated the issue's description above with the code and screenshot

**Comment by wp-user-manager** [comment]
@MarkKevin08 can you try altering your filter to a later priority, eg. `add_filter( 'wpum_get_account_page_tabs', 'wpum_account_change_settings_tab_name', 20 );`

**Comment by MarkKevin08** [comment]
Thanks @wp-user-manager  - replied to the customer.
