### ISSUE TITLE
Allow profile avatar and profile cover images to be added to the registration form

### ISSUE THREAD

**Issue by polevaultweb** [WPUserManager/wp-user-manager#38]
from https://wordpress.org/support/topic/avatar-upload-on-registration-form/

> Enabling the avatar and cover field to work on the registration form should be easy. In file class-wpum-registration-forms-editor.php there’s a variable called “non_allowed_fields”, that holds a list of keys of some fields. Remove the cover field and avatar field from there and it’ll become available from the registration forms editor in the admin panel.

> Once those are enabled, you need to add the logic to store those 2 fields as it’s not available by default in registration forms. To set the storage logic for those 2 fields, open file class-wpum-form-registration.php and locate the method called submit_handler then somewhere after the call to wp_update_user you could add the logic there. You can reuse some of the existing logic from the profile form in file class-wpum-form-profile.php. It’s a bit messy but it does the work.

**Comment by gangesh** [comment]
Is there a possibility doing that without editing actual plugin?

**Comment by polevaultweb** [comment]
No not currently. I'll be including this in the next version 👍

**Comment by gangesh** [comment]
Great! Will look forward to it.
