### ISSUE TITLE
WP User Manager stripping/not following redirect parameters

### ISSUE THREAD

**Issue by MarkKevin08** [WPUserManager/wp-user-manager#382]
## Current Outcome

A client would like to use the WPUM login page, and add a redirect parameter to it.  Like so:
https://staging.protocols.me/umlogin/?redirect_to=https://staging.protocols.me/leave-request/

However, while using WPUM, it does not got anywhere but the login page only, or it strips the redirect parameter from it.

I tried removing all the redirects set from Users >> Settings >> Redirects, but to no avail, the issue remained.

This is working while using the default "/wp-login.php/ ", as an example, the redirect works when using "https://staging.protocols.me/wp-login.php/?redirect_to=https://staging.protocols.me/leave-request/" (while WPUM is deactivated)

## Desired Outcome

the parameters added to the login page set for WPUM should also be working like how the default WordPress login page does it.

## Steps to Reproduce

1. Use a redirect parameter, added to the login page set for WPUM
2. Notice that the parameter will be stripped after logging in.

## Related

- https://secure.helpscout.net/conversation/2297691439/4985/

## Acceptance Criteria

- [ ]

**Comment by wp-user-manager** [comment]
This works currently with `?redirect_to={url}`
