### ISSUE TITLE
Some special characters are being deleted, or not recognized when used within the password field

### ISSUE THREAD

**Issue by MarkKevin08** [WPUserManager/wp-user-manager#384]
## Current Outcome

Upon checking, I was able to replicate what the client mentioned on their ticket:
If users create an account using a password like "Password##%%1234", they encounter the following error message: "Password must be at least 8 characters long and contain at least 1 uppercase letter and 1 number and 1 special character."

Interestingly, if they use a password like "Password#%1234", the account creation process works smoothly. However, the issue arises when attempting to log in,  whether it's through the login form in the header or the backend (wp-admin). The password isn't recognized due to some reason, particularly the percentage symbol (%).

Upon checking from my end, the % symbol gets removed upon registration:
![image](https://github.com/WPUserManager/wp-user-manager/assets/49851476/e89d45ca-c922-4821-a690-3f0bc71c4e66)

## Desired Outcome

The passwords should be accurate, what the users enter within the registration form should be the password that they can use when logging in.

All special characters should be able to be accepted.

## Steps to Reproduce

1. From the registration page, try using either of the following for the password field:
Password##%%1234
Password#%1234

## Related

- https://secure.helpscout.net/conversation/2342321192/5092/

## Acceptance Criteria

- [ ]

**Comment by reygcalantaol** [comment]
@polevaultweb 
The reason for this bug is that the plugin sanitized all the posted values. Should we exclude the password field from sanitization? Please let me know how to proceed.

**Comment by wp-user-manager** [comment]
@reygcalantaol can you see what WordPress does for the wp-login.php password field, ideally we should do the same

**Comment by reygcalantaol** [comment]
@polevaultweb 
WordPress does not sanitize the password field.
