### ISSUE TITLE
Widgets not working when used in the Elementor editor

### ISSUE THREAD

**Issue by MarkKevin08** [WPUserManager/wp-user-manager#386]
## Current Outcome

Currently, when a WPUM widget is used through the Elementor editor, the elements render properly, but the buttons do not work.
No action assigned: action="javascript:void(0);". Submitting the login form is not possible.

## Desired Outcome

Ideally, the integration with Elementor should be working, without any issues.

## Steps to Reproduce

1. Create a log in page
2. Edit through Elementor
3. Add the Login Form Widget
4. Try to log in, and see the error.

## Related

-

## Acceptance Criteria

- [ ]

**Comment by wp-user-manager** [comment]
@reygcalantaol can you take a look please?

**Comment by reygcalantaol** [comment]
@polevaultweb 
The reason for this is the following line of code:
`preg_replace("/<form action=([\"'])(.*?)\"/", '<form action="javascript:void(0);"', $shortcode)`

I can't recall the exact purpose behind doing this. I'll remove it now.
