### ISSUE TITLE
User search form is not displaying on the frontend.

### ISSUE THREAD

**Issue by RobFrtlza** [WPUserManager/wp-user-manager#399]
## Current Outcome

Currently, the user search form is not displaying on the frontend even the option is enabled. Image for reference: https://share.zight.com/2Nu9zjz7

## Desired Outcome

Ideally, the user search form will display on the frontend after activating the option. 

## Steps to Reproduce

1. Navigate to Users > Directories
2. Scroll down to 'Search'
3. Enable 'Display Search Form'
4. Check the directory in the frontend

## Related

[-
](https://secure.helpscout.net/conversation/2515420641/5561?folderId=3207860)
## Acceptance Criteria

- Extra details:

Was able to replicate the reported behavior on my test site.

**Comment by reygcalantaol** [comment]
@RobFrtlza 

Can you give screenshot on how it looks in your frontend.
I can't reproduce the issue. On the attached screenshot the search form is showing.
![image](https://github.com/WPUserManager/wp-user-manager/assets/1219402/5d816b5a-da3a-4d92-af6e-d1c99cd9c2a0)

**Comment by RobFrtlza** [comment]
Sorry, what I mean is the search fields. 
![image](https://github.com/WPUserManager/wp-user-manager/assets/128808133/6d6e1b16-ceab-4f5a-a60d-b4d5d30c8c70)

**Comment by reygcalantaol** [comment]
@RobFrtlza 
I'm still confused.
Are you expecting the search fields to show up in the form in the frontend? That is not how it works. The search fields that were set in the backend simply means that in the frontend, the search string will match all those fields specified in the backend.

**Comment by RobFrtlza** [comment]
@reygcalantaol, thanks for clarification. I'll let the user know about this.
