### ISSUE TITLE
Getting error with show_rest_to_user_directories function

### ISSUE THREAD

**Issue by seanking2919** [WPUserManager/wp-user-manager#96]
In ClassicPress 1.1.2, I'm getting an error saying that is_user_logged_in() is an undefined function even though it really isn't.

Some more specifics:

PHP 7.3.14
nginx 1.17.8

![image](https://user-images.githubusercontent.com/31253278/75410201-47dbf880-58d8-11ea-8ed2-7023558fa81a.png)

**Comment by polevaultweb** [comment]
Apologies! This has been fixed in 2.3.1, just released 🙌
